from datetime import UTC, datetime

from sqlalchemy import JSON, Boolean, Column, Date, DateTime, Float, Integer, Numeric, String, Text

try:
	from .database import Base
except ImportError:
	from database import Base


def utc_now() -> datetime:
	return datetime.now(UTC)


class LoanApplication(Base):
	__tablename__ = "loan_applications"

	id = Column(Integer, primary_key=True, index=True)
	application_id = Column(String(64), unique=True, nullable=False, index=True)
	application_channel = Column(String(64), nullable=False)
	submission_timestamp = Column(DateTime(timezone=True), nullable=False, default=utc_now)
	product_type = Column(String(64), nullable=False)
	prior_decision_reference = Column(String(128), nullable=True)

	requested_loan_amount = Column(Numeric(12, 2), nullable=False)
	requested_term_months = Column(Integer, nullable=False)
	down_payment_amount = Column(Numeric(12, 2), nullable=False, default=0)
	trade_in_value = Column(Numeric(12, 2), nullable=True)
	trade_in_payoff = Column(Numeric(12, 2), nullable=True)

	applicant_id = Column(String(64), nullable=False, index=True)
	applicant_legal_name = Column(String(255), nullable=False)
	applicant_date_of_birth = Column(Date, nullable=False)
	applicant_tax_id_token = Column(String(255), nullable=False)
	applicant_address = Column(Text, nullable=False)
	applicant_state = Column(String(32), nullable=False)
	applicant_residence_duration_months = Column(Integer, nullable=False)
	applicant_employment_status = Column(String(64), nullable=False)
	applicant_employer_name = Column(String(255), nullable=True)
	applicant_employment_duration_months = Column(Integer, nullable=True)
	applicant_monthly_gross_income = Column(Numeric(12, 2), nullable=False)
	applicant_monthly_housing_payment = Column(Numeric(12, 2), nullable=False, default=0)
	applicant_credit_score = Column(Integer, nullable=False)
	applicant_credit_history_depth_months = Column(Integer, nullable=True)
	applicant_recent_delinquencies = Column(Integer, nullable=False, default=0)
	applicant_recent_severe_delinquencies = Column(Integer, nullable=False, default=0)
	applicant_bankruptcies = Column(Integer, nullable=False, default=0)
	applicant_open_bankruptcy = Column(Boolean, nullable=False, default=False)
	applicant_recent_repossessions = Column(Integer, nullable=False, default=0)
	applicant_charge_offs = Column(Integer, nullable=False, default=0)
	applicant_recent_inquiries = Column(Integer, nullable=False, default=0)
	applicant_tradeline_history = Column(JSON, nullable=True)
	applicant_credit_bureau_attributes = Column(JSON, nullable=True)
	applicant_identity_verified = Column(Boolean, nullable=False, default=False)
	applicant_fraud_flag = Column(Boolean, nullable=False, default=False)
	applicant_synthetic_identity_flag = Column(Boolean, nullable=False, default=False)
	applicant_sanctions_flag = Column(Boolean, nullable=False, default=False)
	applicant_tax_id_valid = Column(Boolean, nullable=False, default=True)
	applicant_deceased_tax_id_flag = Column(Boolean, nullable=False, default=False)
	applicant_prior_fraud_investigation = Column(Boolean, nullable=False, default=False)
	applicant_prior_first_payment_default_investigation = Column(Boolean, nullable=False, default=False)
	applicant_prior_positive_lender_relationship = Column(Boolean, nullable=False, default=False)

	has_co_applicant = Column(Boolean, nullable=False, default=False)
	co_applicant_id = Column(String(64), nullable=True, index=True)
	co_applicant_legal_name = Column(String(255), nullable=True)
	co_applicant_date_of_birth = Column(Date, nullable=True)
	co_applicant_tax_id_token = Column(String(255), nullable=True)
	co_applicant_address = Column(Text, nullable=True)
	co_applicant_state = Column(String(32), nullable=True)
	co_applicant_residence_duration_months = Column(Integer, nullable=True)
	co_applicant_employment_status = Column(String(64), nullable=True)
	co_applicant_employer_name = Column(String(255), nullable=True)
	co_applicant_employment_duration_months = Column(Integer, nullable=True)
	co_applicant_monthly_gross_income = Column(Numeric(12, 2), nullable=True)
	co_applicant_monthly_housing_payment = Column(Numeric(12, 2), nullable=True)
	co_applicant_credit_score = Column(Integer, nullable=True)
	co_applicant_credit_history_depth_months = Column(Integer, nullable=True)
	co_applicant_recent_delinquencies = Column(Integer, nullable=True)
	co_applicant_recent_severe_delinquencies = Column(Integer, nullable=True)
	co_applicant_bankruptcies = Column(Integer, nullable=True)
	co_applicant_open_bankruptcy = Column(Boolean, nullable=True)
	co_applicant_recent_repossessions = Column(Integer, nullable=True)
	co_applicant_charge_offs = Column(Integer, nullable=True)
	co_applicant_recent_inquiries = Column(Integer, nullable=True)
	co_applicant_tradeline_history = Column(JSON, nullable=True)
	co_applicant_credit_bureau_attributes = Column(JSON, nullable=True)
	co_applicant_identity_verified = Column(Boolean, nullable=True)
	co_applicant_fraud_flag = Column(Boolean, nullable=True)
	co_applicant_synthetic_identity_flag = Column(Boolean, nullable=True)
	co_applicant_sanctions_flag = Column(Boolean, nullable=True)
	co_applicant_tax_id_valid = Column(Boolean, nullable=True)
	co_applicant_deceased_tax_id_flag = Column(Boolean, nullable=True)

	vin = Column(String(32), nullable=False, index=True)
	vehicle_model_year = Column(Integer, nullable=False)
	vehicle_make = Column(String(128), nullable=False)
	vehicle_model = Column(String(128), nullable=False)
	vehicle_trim = Column(String(128), nullable=True)
	vehicle_new_or_used = Column(String(32), nullable=False)
	vehicle_mileage = Column(Integer, nullable=False)
	vehicle_valuation_source = Column(String(128), nullable=False)
	vehicle_value = Column(Numeric(12, 2), nullable=False)
	vehicle_title_status = Column(String(64), nullable=False)
	vehicle_use = Column(String(64), nullable=False)
	vehicle_type = Column(String(64), nullable=False)
	dealer_listed_price = Column(Numeric(12, 2), nullable=False)
	warranty_amount = Column(Numeric(12, 2), nullable=False, default=0)
	gap_amount = Column(Numeric(12, 2), nullable=False, default=0)
	backend_product_amount = Column(Numeric(12, 2), nullable=False, default=0)
	add_ons_amount = Column(Numeric(12, 2), nullable=False, default=0)
	negative_equity_amount = Column(Numeric(12, 2), nullable=False, default=0)
	vin_decoded = Column(Boolean, nullable=False, default=False)

	dealer_id = Column(String(64), nullable=False, index=True)
	dealer_status = Column(String(64), nullable=False)
	dealer_risk_rating = Column(String(64), nullable=False)
	dealer_default_rate = Column(Float, nullable=True)
	dealer_first_payment_default_rate = Column(Float, nullable=True)
	dealer_buyback_history = Column(JSON, nullable=True)
	dealer_buyback_frequency = Column(Float, nullable=True)
	dealer_contract_defect_rate = Column(Float, nullable=True)
	dealer_fraud_flag = Column(Boolean, nullable=False, default=False)
	dealer_complaint_rate = Column(Float, nullable=True)
	dealer_max_ltv_override = Column(Float, nullable=True)
	dealer_program_eligibility = Column(JSON, nullable=True)
	dealer_state = Column(String(32), nullable=False)
	dealer_license_status = Column(String(64), nullable=False)
	dealer_prior_exception_usage = Column(Integer, nullable=False, default=0)

	loan_to_value_ratio = Column(Float, nullable=True)
	payment_to_income_ratio = Column(Float, nullable=True)
	debt_to_income_ratio = Column(Float, nullable=True)
	amount_financed = Column(Numeric(12, 2), nullable=True)
	net_trade_equity = Column(Numeric(12, 2), nullable=True)
	vehicle_age_years = Column(Integer, nullable=True)
	applicant_age_years = Column(Integer, nullable=True)
	co_applicant_age_years = Column(Integer, nullable=True)
	combined_monthly_income = Column(Numeric(12, 2), nullable=True)
	credit_score_band = Column(String(32), nullable=True)
	risk_tier_candidate = Column(String(16), nullable=True)
	final_risk_tier = Column(String(16), nullable=True)
	dealer_overlay_category = Column(String(64), nullable=True)

	decision_outcome = Column(String(64), nullable=True)
	rule_version = Column(String(64), nullable=True)
	decline_reasons = Column(JSON, nullable=True)
	stipulations = Column(JSON, nullable=True)
	manual_review_reasons = Column(JSON, nullable=True)
	triggered_rules = Column(JSON, nullable=True)
	passed_rules = Column(JSON, nullable=True)
	dealer_overlay_result = Column(JSON, nullable=True)
	vehicle_eligibility_result = Column(JSON, nullable=True)
	audit_correlation_id = Column(String(128), nullable=True, index=True)
	evaluated_at = Column(DateTime(timezone=True), nullable=True)

	created_at = Column(DateTime(timezone=True), nullable=False, default=utc_now)
	updated_at = Column(DateTime(timezone=True), nullable=False, default=utc_now, onupdate=utc_now)


class ApplicationStatusAudit(Base):
	__tablename__ = "application_status_audit"

	id = Column(Integer, primary_key=True, index=True)
	application_id = Column(String(64), nullable=False, index=True)
	previous_status = Column(String(64), nullable=True)
	new_status = Column(String(64), nullable=False)
	changed_by = Column(String(128), nullable=False)
	changed_by_role = Column(String(32), nullable=False)
	change_reason = Column(String(128), nullable=False)
	audit_correlation_id = Column(String(128), nullable=True, index=True)
	created_at = Column(DateTime(timezone=True), nullable=False, default=utc_now)
